easy_admin:
  design:
    form_theme:
      - "@EasyAdmin/form/bootstrap_4.html.twig" # required for ckeditor integration
      - "@FOSCKEditor/Form/ckeditor_widget.html.twig" # required for ckeditor integration
