easy_admin:
  entities:
    User:
      class: App\Entity\User
      label: 'admin.entity.user.user'
      controller: App\Controller\Admin\AdminController
      list:
        fields:
          - {property: 'login', label: 'admin.entity.user.security.login'}
          - {property: 'profile', label: 'admin.entity.user.security.profile'}
      form:
        fields:
          - { property: 'login', type: 'text', type_options: { required: false, label: 'admin.entity.user.security.login' }}
          - { property: 'plainPassword', type: 'password', type_options: { required: false, label: 'admin.entity.user.security.password' }}
          - { property: 'profile', type: 'choice', type_options: { multiple: false, expanded: true, label: 'admin.entity.user.security.profile' , choices: { 'admin.entity.user.user':!php/const App\Entity\User::PROFILE_USER , 'admin.entity.user.admin':!php/const App\Entity\User::PROFILE_ADMIN}} }
